apiVersion: apps/v1
kind: Deployment
metadata:
  name: exploit-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exploit
  template:
    metadata:
      labels:
        app: exploit
    spec:
      containers:
      - name: main
        image: nginx:alpine
